-- regnskap-sync cron schedule — RUNBOOK / REFERENCE.
--
-- Live schedule:
--   Aktivert i Supabase pg_cron som jobben 'regnskap-sync-15min'
--   med catchup-profil hvert 15. minutt, forskjøvet fra NAV/Careerjet
--   (13,28,43,58 * * * *) via migrasjonen
--   20260805184332_regnskap_sync_cron_delivery_relief.sql. Cron-secret hentes
--   fra vault.decrypted_secrets ('regnskap_sync_cron_secret') ved hvert
--   kall; samme verdi ligger som Edge Function env REGNSKAP_SYNC_CRON_SECRET.
--
-- Denne filen beholdes som referanse hvis jobben må gjenopprettes manuelt
-- (f.eks. etter restore eller migrering). Body og defaults skal matche
-- live migrasjon: mode=due, limit=60, rps=2, timeBudgetMs=55000,
-- includePdfYears=false, timeout_milliseconds=150000. Dette prioriterer rask
-- speiling av minst ett regnskapsår; PDF-år kan hentes senere.

-- Manuell (re)schedule — kjør kun ved behov:
-- SELECT cron.schedule(
--   'regnskap-sync-15min',
--   '13,28,43,58 * * * *',
--   $$
--   SELECT net.http_post(
--     url := 'https://miwzhbludgwvskmsfqnq.supabase.co/functions/v1/regnskap-sync',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-cron-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'regnskap_sync_cron_secret')
--     ),
--     body := '{
--       "op": "run",
--       "mode": "due",
--       "limit": 60,
--       "rps": 2,
--       "timeBudgetMs": 55000,
--       "includePdfYears": false,
--       "meta": {
--         "profile": "catchup_min_1_year",
--         "scheduledBy": "pg_cron",
--         "deliveryProfile": "relief_15m_offset"
--       }
--     }'::jsonb,
--     timeout_milliseconds := 150000
--   ) AS request_id;
--   $$
-- );

-- Avregistrering ved behov:
-- SELECT cron.unschedule('regnskap-sync-15min');

-- Inspisere leveranser (admin-only RPC):
-- SELECT * FROM public.list_regnskap_cron_runs(20);
--
-- Merknad: pg_net-respons i dette prosjektet eksponeres via net._http_response.
