/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelskapsanalyseRouteImport } from './routes/selskapsanalyse'
import { Route as RekruttererundersokelseRouteImport } from './routes/rekruttererundersokelse'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as MarkedsinnsiktRouteImport } from './routes/markedsinnsikt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArbeidsgivereRouteImport } from './routes/arbeidsgivere'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelskapsanalyseIndexRouteImport } from './routes/selskapsanalyse.index'
import { Route as RekruttererundersokelseIndexRouteImport } from './routes/rekruttererundersokelse.index'
import { Route as ArbeidsgivereIndexRouteImport } from './routes/arbeidsgivere.index'
import { Route as SelskapsanalyseTakkRouteImport } from './routes/selskapsanalyse.takk'
import { Route as RekruttererundersokelseTakkRouteImport } from './routes/rekruttererundersokelse.takk'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthLinkedinCallbackRouteImport } from './routes/auth.linkedin-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArbeidsgivereOrgnrRouteImport } from './routes/arbeidsgivere.$orgnr'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedMyApplicationsRouteImport } from './routes/_authenticated/my-applications'
import { Route as AuthenticatedJobLeadsRouteImport } from './routes/_authenticated/job-leads'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoverLettersRouteImport } from './routes/_authenticated/cover-letters'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAboutMeRouteImport } from './routes/_authenticated/about-me'
import { Route as SelskapsanalyseAnalysedatabaseIndexRouteImport } from './routes/selskapsanalyse.analysedatabase.index'
import { Route as RekruttererundersokelseResultaterIndexRouteImport } from './routes/rekruttererundersokelse.resultater.index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOfferAnalysisIndexRouteImport } from './routes/_authenticated/offer-analysis/index'
import { Route as AuthenticatedNextStepsIndexRouteImport } from './routes/_authenticated/next-steps/index'
import { Route as AuthenticatedInterviewPrepIndexRouteImport } from './routes/_authenticated/interview-prep/index'
import { Route as AuthenticatedEmployersIndexRouteImport } from './routes/_authenticated/employers/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDocumentationIndexRouteImport } from './routes/_authenticated/documentation/index'
import { Route as AuthenticatedCvBuilderIndexRouteImport } from './routes/_authenticated/cv-builder/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SelskapsanalyseAnalysedatabaseIdRouteImport } from './routes/selskapsanalyse.analysedatabase.$id'
import { Route as RekruttererundersokelseResultaterFullRouteImport } from './routes/rekruttererundersokelse.resultater.full'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicIngestReportRouteImport } from './routes/api/public/ingest-report'
import { Route as AuthenticatedEmployersCompanyIdRouteImport } from './routes/_authenticated/employers/$companyId'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents/new'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents/$id'
import { Route as AuthenticatedDocumentationPackagesRouteImport } from './routes/_authenticated/documentation/packages'
import { Route as AuthenticatedDocumentationLibraryRouteImport } from './routes/_authenticated/documentation/library'
import { Route as AuthenticatedDocumentationCasesRouteImport } from './routes/_authenticated/documentation/cases'
import { Route as AuthenticatedCareerAtomReviewRouteImport } from './routes/_authenticated/career/atom-review'
import { Route as AuthenticatedApplicationsNewRouteImport } from './routes/_authenticated/applications/new'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications/$id'
import { Route as AuthenticatedAdminRekruttererundersokelseRouteImport } from './routes/_authenticated/admin.rekruttererundersokelse'
import { Route as AuthenticatedAdminRegnskapRouteImport } from './routes/_authenticated/admin.regnskap'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminCvTestRouteImport } from './routes/_authenticated/admin.cv-test'
import { Route as AuthenticatedAdminChangelogRouteImport } from './routes/_authenticated/admin.changelog'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicSelskapsanalysePreviewEmailRouteImport } from './routes/api/public/selskapsanalyse/preview-email'
import { Route as ApiPublicSelskapsanalyseDownloadRouteImport } from './routes/api/public/selskapsanalyse/download'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelskapsanalyseRoute = SelskapsanalyseRouteImport.update({
  id: '/selskapsanalyse',
  path: '/selskapsanalyse',
  getParentRoute: () => rootRouteImport,
} as any)
const RekruttererundersokelseRoute = RekruttererundersokelseRouteImport.update({
  id: '/rekruttererundersokelse',
  path: '/rekruttererundersokelse',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkedsinnsiktRoute = MarkedsinnsiktRouteImport.update({
  id: '/markedsinnsikt',
  path: '/markedsinnsikt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbeidsgivereRoute = ArbeidsgivereRouteImport.update({
  id: '/arbeidsgivere',
  path: '/arbeidsgivere',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelskapsanalyseIndexRoute = SelskapsanalyseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SelskapsanalyseRoute,
} as any)
const RekruttererundersokelseIndexRoute =
  RekruttererundersokelseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RekruttererundersokelseRoute,
  } as any)
const ArbeidsgivereIndexRoute = ArbeidsgivereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArbeidsgivereRoute,
} as any)
const SelskapsanalyseTakkRoute = SelskapsanalyseTakkRouteImport.update({
  id: '/takk',
  path: '/takk',
  getParentRoute: () => SelskapsanalyseRoute,
} as any)
const RekruttererundersokelseTakkRoute =
  RekruttererundersokelseTakkRouteImport.update({
    id: '/takk',
    path: '/takk',
    getParentRoute: () => RekruttererundersokelseRoute,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkedinCallbackRoute = AuthLinkedinCallbackRouteImport.update({
  id: '/auth/linkedin-callback',
  path: '/auth/linkedin-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbeidsgivereOrgnrRoute = ArbeidsgivereOrgnrRouteImport.update({
  id: '/$orgnr',
  path: '/$orgnr',
  getParentRoute: () => ArbeidsgivereRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyApplicationsRoute =
  AuthenticatedMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobLeadsRoute = AuthenticatedJobLeadsRouteImport.update({
  id: '/job-leads',
  path: '/job-leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoverLettersRoute =
  AuthenticatedCoverLettersRouteImport.update({
    id: '/cover-letters',
    path: '/cover-letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutMeRoute = AuthenticatedAboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SelskapsanalyseAnalysedatabaseIndexRoute =
  SelskapsanalyseAnalysedatabaseIndexRouteImport.update({
    id: '/analysedatabase/',
    path: '/analysedatabase/',
    getParentRoute: () => SelskapsanalyseRoute,
  } as any)
const RekruttererundersokelseResultaterIndexRoute =
  RekruttererundersokelseResultaterIndexRouteImport.update({
    id: '/resultater/',
    path: '/resultater/',
    getParentRoute: () => RekruttererundersokelseRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfferAnalysisIndexRoute =
  AuthenticatedOfferAnalysisIndexRouteImport.update({
    id: '/offer-analysis/',
    path: '/offer-analysis/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNextStepsIndexRoute =
  AuthenticatedNextStepsIndexRouteImport.update({
    id: '/next-steps/',
    path: '/next-steps/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewPrepIndexRoute =
  AuthenticatedInterviewPrepIndexRouteImport.update({
    id: '/interview-prep/',
    path: '/interview-prep/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployersIndexRoute =
  AuthenticatedEmployersIndexRouteImport.update({
    id: '/employers/',
    path: '/employers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentationIndexRoute =
  AuthenticatedDocumentationIndexRouteImport.update({
    id: '/documentation/',
    path: '/documentation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCvBuilderIndexRoute =
  AuthenticatedCvBuilderIndexRouteImport.update({
    id: '/cv-builder/',
    path: '/cv-builder/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SelskapsanalyseAnalysedatabaseIdRoute =
  SelskapsanalyseAnalysedatabaseIdRouteImport.update({
    id: '/analysedatabase/$id',
    path: '/analysedatabase/$id',
    getParentRoute: () => SelskapsanalyseRoute,
  } as any)
const RekruttererundersokelseResultaterFullRoute =
  RekruttererundersokelseResultaterFullRouteImport.update({
    id: '/resultater/full',
    path: '/resultater/full',
    getParentRoute: () => RekruttererundersokelseRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestReportRoute = ApiPublicIngestReportRouteImport.update({
  id: '/api/public/ingest-report',
  path: '/api/public/ingest-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmployersCompanyIdRoute =
  AuthenticatedEmployersCompanyIdRouteImport.update({
    id: '/employers/$companyId',
    path: '/employers/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentationPackagesRoute =
  AuthenticatedDocumentationPackagesRouteImport.update({
    id: '/documentation/packages',
    path: '/documentation/packages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentationLibraryRoute =
  AuthenticatedDocumentationLibraryRouteImport.update({
    id: '/documentation/library',
    path: '/documentation/library',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentationCasesRoute =
  AuthenticatedDocumentationCasesRouteImport.update({
    id: '/documentation/cases',
    path: '/documentation/cases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareerAtomReviewRoute =
  AuthenticatedCareerAtomReviewRouteImport.update({
    id: '/career/atom-review',
    path: '/career/atom-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsNewRoute =
  AuthenticatedApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRekruttererundersokelseRoute =
  AuthenticatedAdminRekruttererundersokelseRouteImport.update({
    id: '/admin/rekruttererundersokelse',
    path: '/admin/rekruttererundersokelse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRegnskapRoute =
  AuthenticatedAdminRegnskapRouteImport.update({
    id: '/admin/regnskap',
    path: '/admin/regnskap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCvTestRoute =
  AuthenticatedAdminCvTestRouteImport.update({
    id: '/admin/cv-test',
    path: '/admin/cv-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminChangelogRoute =
  AuthenticatedAdminChangelogRouteImport.update({
    id: '/admin/changelog',
    path: '/admin/changelog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSelskapsanalysePreviewEmailRoute =
  ApiPublicSelskapsanalysePreviewEmailRouteImport.update({
    id: '/api/public/selskapsanalyse/preview-email',
    path: '/api/public/selskapsanalyse/preview-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSelskapsanalyseDownloadRoute =
  ApiPublicSelskapsanalyseDownloadRouteImport.update({
    id: '/api/public/selskapsanalyse/download',
    path: '/api/public/selskapsanalyse/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbeidsgivere': typeof ArbeidsgivereRouteWithChildren
  '/login': typeof LoginRoute
  '/markedsinnsikt': typeof MarkedsinnsiktRoute
  '/personvern': typeof PersonvernRoute
  '/rekruttererundersokelse': typeof RekruttererundersokelseRouteWithChildren
  '/selskapsanalyse': typeof SelskapsanalyseRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/about-me': typeof AuthenticatedAboutMeRoute
  '/app': typeof AuthenticatedAppRoute
  '/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/job-leads': typeof AuthenticatedJobLeadsRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/arbeidsgivere/$orgnr': typeof ArbeidsgivereOrgnrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/linkedin-callback': typeof AuthLinkedinCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/rekruttererundersokelse/takk': typeof RekruttererundersokelseTakkRoute
  '/selskapsanalyse/takk': typeof SelskapsanalyseTakkRoute
  '/arbeidsgivere/': typeof ArbeidsgivereIndexRoute
  '/rekruttererundersokelse/': typeof RekruttererundersokelseIndexRoute
  '/selskapsanalyse/': typeof SelskapsanalyseIndexRoute
  '/admin/changelog': typeof AuthenticatedAdminChangelogRoute
  '/admin/cv-test': typeof AuthenticatedAdminCvTestRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/regnskap': typeof AuthenticatedAdminRegnskapRoute
  '/admin/rekruttererundersokelse': typeof AuthenticatedAdminRekruttererundersokelseRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/career/atom-review': typeof AuthenticatedCareerAtomReviewRoute
  '/documentation/cases': typeof AuthenticatedDocumentationCasesRoute
  '/documentation/library': typeof AuthenticatedDocumentationLibraryRoute
  '/documentation/packages': typeof AuthenticatedDocumentationPackagesRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/employers/$companyId': typeof AuthenticatedEmployersCompanyIdRoute
  '/api/public/ingest-report': typeof ApiPublicIngestReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/rekruttererundersokelse/resultater/full': typeof RekruttererundersokelseResultaterFullRoute
  '/selskapsanalyse/analysedatabase/$id': typeof SelskapsanalyseAnalysedatabaseIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/cv-builder/': typeof AuthenticatedCvBuilderIndexRoute
  '/documentation/': typeof AuthenticatedDocumentationIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/employers/': typeof AuthenticatedEmployersIndexRoute
  '/interview-prep/': typeof AuthenticatedInterviewPrepIndexRoute
  '/next-steps/': typeof AuthenticatedNextStepsIndexRoute
  '/offer-analysis/': typeof AuthenticatedOfferAnalysisIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/rekruttererundersokelse/resultater/': typeof RekruttererundersokelseResultaterIndexRoute
  '/selskapsanalyse/analysedatabase/': typeof SelskapsanalyseAnalysedatabaseIndexRoute
  '/api/public/selskapsanalyse/download': typeof ApiPublicSelskapsanalyseDownloadRoute
  '/api/public/selskapsanalyse/preview-email': typeof ApiPublicSelskapsanalysePreviewEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markedsinnsikt': typeof MarkedsinnsiktRoute
  '/personvern': typeof PersonvernRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/about-me': typeof AuthenticatedAboutMeRoute
  '/app': typeof AuthenticatedAppRoute
  '/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/job-leads': typeof AuthenticatedJobLeadsRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/arbeidsgivere/$orgnr': typeof ArbeidsgivereOrgnrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/linkedin-callback': typeof AuthLinkedinCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/rekruttererundersokelse/takk': typeof RekruttererundersokelseTakkRoute
  '/selskapsanalyse/takk': typeof SelskapsanalyseTakkRoute
  '/arbeidsgivere': typeof ArbeidsgivereIndexRoute
  '/rekruttererundersokelse': typeof RekruttererundersokelseIndexRoute
  '/selskapsanalyse': typeof SelskapsanalyseIndexRoute
  '/admin/changelog': typeof AuthenticatedAdminChangelogRoute
  '/admin/cv-test': typeof AuthenticatedAdminCvTestRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/regnskap': typeof AuthenticatedAdminRegnskapRoute
  '/admin/rekruttererundersokelse': typeof AuthenticatedAdminRekruttererundersokelseRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/career/atom-review': typeof AuthenticatedCareerAtomReviewRoute
  '/documentation/cases': typeof AuthenticatedDocumentationCasesRoute
  '/documentation/library': typeof AuthenticatedDocumentationLibraryRoute
  '/documentation/packages': typeof AuthenticatedDocumentationPackagesRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/employers/$companyId': typeof AuthenticatedEmployersCompanyIdRoute
  '/api/public/ingest-report': typeof ApiPublicIngestReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/rekruttererundersokelse/resultater/full': typeof RekruttererundersokelseResultaterFullRoute
  '/selskapsanalyse/analysedatabase/$id': typeof SelskapsanalyseAnalysedatabaseIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/cv-builder': typeof AuthenticatedCvBuilderIndexRoute
  '/documentation': typeof AuthenticatedDocumentationIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/employers': typeof AuthenticatedEmployersIndexRoute
  '/interview-prep': typeof AuthenticatedInterviewPrepIndexRoute
  '/next-steps': typeof AuthenticatedNextStepsIndexRoute
  '/offer-analysis': typeof AuthenticatedOfferAnalysisIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/rekruttererundersokelse/resultater': typeof RekruttererundersokelseResultaterIndexRoute
  '/selskapsanalyse/analysedatabase': typeof SelskapsanalyseAnalysedatabaseIndexRoute
  '/api/public/selskapsanalyse/download': typeof ApiPublicSelskapsanalyseDownloadRoute
  '/api/public/selskapsanalyse/preview-email': typeof ApiPublicSelskapsanalysePreviewEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/arbeidsgivere': typeof ArbeidsgivereRouteWithChildren
  '/login': typeof LoginRoute
  '/markedsinnsikt': typeof MarkedsinnsiktRoute
  '/personvern': typeof PersonvernRoute
  '/rekruttererundersokelse': typeof RekruttererundersokelseRouteWithChildren
  '/selskapsanalyse': typeof SelskapsanalyseRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/about-me': typeof AuthenticatedAboutMeRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/job-leads': typeof AuthenticatedJobLeadsRoute
  '/_authenticated/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/arbeidsgivere/$orgnr': typeof ArbeidsgivereOrgnrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/linkedin-callback': typeof AuthLinkedinCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/rekruttererundersokelse/takk': typeof RekruttererundersokelseTakkRoute
  '/selskapsanalyse/takk': typeof SelskapsanalyseTakkRoute
  '/arbeidsgivere/': typeof ArbeidsgivereIndexRoute
  '/rekruttererundersokelse/': typeof RekruttererundersokelseIndexRoute
  '/selskapsanalyse/': typeof SelskapsanalyseIndexRoute
  '/_authenticated/admin/changelog': typeof AuthenticatedAdminChangelogRoute
  '/_authenticated/admin/cv-test': typeof AuthenticatedAdminCvTestRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/regnskap': typeof AuthenticatedAdminRegnskapRoute
  '/_authenticated/admin/rekruttererundersokelse': typeof AuthenticatedAdminRekruttererundersokelseRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/_authenticated/career/atom-review': typeof AuthenticatedCareerAtomReviewRoute
  '/_authenticated/documentation/cases': typeof AuthenticatedDocumentationCasesRoute
  '/_authenticated/documentation/library': typeof AuthenticatedDocumentationLibraryRoute
  '/_authenticated/documentation/packages': typeof AuthenticatedDocumentationPackagesRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/_authenticated/employers/$companyId': typeof AuthenticatedEmployersCompanyIdRoute
  '/api/public/ingest-report': typeof ApiPublicIngestReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/rekruttererundersokelse/resultater/full': typeof RekruttererundersokelseResultaterFullRoute
  '/selskapsanalyse/analysedatabase/$id': typeof SelskapsanalyseAnalysedatabaseIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/cv-builder/': typeof AuthenticatedCvBuilderIndexRoute
  '/_authenticated/documentation/': typeof AuthenticatedDocumentationIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/employers/': typeof AuthenticatedEmployersIndexRoute
  '/_authenticated/interview-prep/': typeof AuthenticatedInterviewPrepIndexRoute
  '/_authenticated/next-steps/': typeof AuthenticatedNextStepsIndexRoute
  '/_authenticated/offer-analysis/': typeof AuthenticatedOfferAnalysisIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/rekruttererundersokelse/resultater/': typeof RekruttererundersokelseResultaterIndexRoute
  '/selskapsanalyse/analysedatabase/': typeof SelskapsanalyseAnalysedatabaseIndexRoute
  '/api/public/selskapsanalyse/download': typeof ApiPublicSelskapsanalyseDownloadRoute
  '/api/public/selskapsanalyse/preview-email': typeof ApiPublicSelskapsanalysePreviewEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbeidsgivere'
    | '/login'
    | '/markedsinnsikt'
    | '/personvern'
    | '/rekruttererundersokelse'
    | '/selskapsanalyse'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/about-me'
    | '/app'
    | '/cover-letters'
    | '/dashboard'
    | '/integrations'
    | '/job-leads'
    | '/my-applications'
    | '/preferences'
    | '/arbeidsgivere/$orgnr'
    | '/auth/callback'
    | '/auth/linkedin-callback'
    | '/email/unsubscribe'
    | '/rekruttererundersokelse/takk'
    | '/selskapsanalyse/takk'
    | '/arbeidsgivere/'
    | '/rekruttererundersokelse/'
    | '/selskapsanalyse/'
    | '/admin/changelog'
    | '/admin/cv-test'
    | '/admin/leads'
    | '/admin/regnskap'
    | '/admin/rekruttererundersokelse'
    | '/applications/$id'
    | '/applications/new'
    | '/career/atom-review'
    | '/documentation/cases'
    | '/documentation/library'
    | '/documentation/packages'
    | '/documents/$id'
    | '/documents/new'
    | '/employers/$companyId'
    | '/api/public/ingest-report'
    | '/lovable/email/suppression'
    | '/rekruttererundersokelse/resultater/full'
    | '/selskapsanalyse/analysedatabase/$id'
    | '/admin/'
    | '/applications/'
    | '/cv-builder/'
    | '/documentation/'
    | '/documents/'
    | '/employers/'
    | '/interview-prep/'
    | '/next-steps/'
    | '/offer-analysis/'
    | '/onboarding/'
    | '/rekruttererundersokelse/resultater/'
    | '/selskapsanalyse/analysedatabase/'
    | '/api/public/selskapsanalyse/download'
    | '/api/public/selskapsanalyse/preview-email'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/markedsinnsikt'
    | '/personvern'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/about-me'
    | '/app'
    | '/cover-letters'
    | '/dashboard'
    | '/integrations'
    | '/job-leads'
    | '/my-applications'
    | '/preferences'
    | '/arbeidsgivere/$orgnr'
    | '/auth/callback'
    | '/auth/linkedin-callback'
    | '/email/unsubscribe'
    | '/rekruttererundersokelse/takk'
    | '/selskapsanalyse/takk'
    | '/arbeidsgivere'
    | '/rekruttererundersokelse'
    | '/selskapsanalyse'
    | '/admin/changelog'
    | '/admin/cv-test'
    | '/admin/leads'
    | '/admin/regnskap'
    | '/admin/rekruttererundersokelse'
    | '/applications/$id'
    | '/applications/new'
    | '/career/atom-review'
    | '/documentation/cases'
    | '/documentation/library'
    | '/documentation/packages'
    | '/documents/$id'
    | '/documents/new'
    | '/employers/$companyId'
    | '/api/public/ingest-report'
    | '/lovable/email/suppression'
    | '/rekruttererundersokelse/resultater/full'
    | '/selskapsanalyse/analysedatabase/$id'
    | '/admin'
    | '/applications'
    | '/cv-builder'
    | '/documentation'
    | '/documents'
    | '/employers'
    | '/interview-prep'
    | '/next-steps'
    | '/offer-analysis'
    | '/onboarding'
    | '/rekruttererundersokelse/resultater'
    | '/selskapsanalyse/analysedatabase'
    | '/api/public/selskapsanalyse/download'
    | '/api/public/selskapsanalyse/preview-email'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/arbeidsgivere'
    | '/login'
    | '/markedsinnsikt'
    | '/personvern'
    | '/rekruttererundersokelse'
    | '/selskapsanalyse'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authenticated/about-me'
    | '/_authenticated/app'
    | '/_authenticated/cover-letters'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/job-leads'
    | '/_authenticated/my-applications'
    | '/_authenticated/preferences'
    | '/arbeidsgivere/$orgnr'
    | '/auth/callback'
    | '/auth/linkedin-callback'
    | '/email/unsubscribe'
    | '/rekruttererundersokelse/takk'
    | '/selskapsanalyse/takk'
    | '/arbeidsgivere/'
    | '/rekruttererundersokelse/'
    | '/selskapsanalyse/'
    | '/_authenticated/admin/changelog'
    | '/_authenticated/admin/cv-test'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/regnskap'
    | '/_authenticated/admin/rekruttererundersokelse'
    | '/_authenticated/applications/$id'
    | '/_authenticated/applications/new'
    | '/_authenticated/career/atom-review'
    | '/_authenticated/documentation/cases'
    | '/_authenticated/documentation/library'
    | '/_authenticated/documentation/packages'
    | '/_authenticated/documents/$id'
    | '/_authenticated/documents/new'
    | '/_authenticated/employers/$companyId'
    | '/api/public/ingest-report'
    | '/lovable/email/suppression'
    | '/rekruttererundersokelse/resultater/full'
    | '/selskapsanalyse/analysedatabase/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/applications/'
    | '/_authenticated/cv-builder/'
    | '/_authenticated/documentation/'
    | '/_authenticated/documents/'
    | '/_authenticated/employers/'
    | '/_authenticated/interview-prep/'
    | '/_authenticated/next-steps/'
    | '/_authenticated/offer-analysis/'
    | '/_authenticated/onboarding/'
    | '/rekruttererundersokelse/resultater/'
    | '/selskapsanalyse/analysedatabase/'
    | '/api/public/selskapsanalyse/download'
    | '/api/public/selskapsanalyse/preview-email'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ArbeidsgivereRoute: typeof ArbeidsgivereRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarkedsinnsiktRoute: typeof MarkedsinnsiktRoute
  PersonvernRoute: typeof PersonvernRoute
  RekruttererundersokelseRoute: typeof RekruttererundersokelseRouteWithChildren
  SelskapsanalyseRoute: typeof SelskapsanalyseRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLinkedinCallbackRoute: typeof AuthLinkedinCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicIngestReportRoute: typeof ApiPublicIngestReportRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicSelskapsanalyseDownloadRoute: typeof ApiPublicSelskapsanalyseDownloadRoute
  ApiPublicSelskapsanalysePreviewEmailRoute: typeof ApiPublicSelskapsanalysePreviewEmailRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selskapsanalyse': {
      id: '/selskapsanalyse'
      path: '/selskapsanalyse'
      fullPath: '/selskapsanalyse'
      preLoaderRoute: typeof SelskapsanalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekruttererundersokelse': {
      id: '/rekruttererundersokelse'
      path: '/rekruttererundersokelse'
      fullPath: '/rekruttererundersokelse'
      preLoaderRoute: typeof RekruttererundersokelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markedsinnsikt': {
      id: '/markedsinnsikt'
      path: '/markedsinnsikt'
      fullPath: '/markedsinnsikt'
      preLoaderRoute: typeof MarkedsinnsiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbeidsgivere': {
      id: '/arbeidsgivere'
      path: '/arbeidsgivere'
      fullPath: '/arbeidsgivere'
      preLoaderRoute: typeof ArbeidsgivereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selskapsanalyse/': {
      id: '/selskapsanalyse/'
      path: '/'
      fullPath: '/selskapsanalyse/'
      preLoaderRoute: typeof SelskapsanalyseIndexRouteImport
      parentRoute: typeof SelskapsanalyseRoute
    }
    '/rekruttererundersokelse/': {
      id: '/rekruttererundersokelse/'
      path: '/'
      fullPath: '/rekruttererundersokelse/'
      preLoaderRoute: typeof RekruttererundersokelseIndexRouteImport
      parentRoute: typeof RekruttererundersokelseRoute
    }
    '/arbeidsgivere/': {
      id: '/arbeidsgivere/'
      path: '/'
      fullPath: '/arbeidsgivere/'
      preLoaderRoute: typeof ArbeidsgivereIndexRouteImport
      parentRoute: typeof ArbeidsgivereRoute
    }
    '/selskapsanalyse/takk': {
      id: '/selskapsanalyse/takk'
      path: '/takk'
      fullPath: '/selskapsanalyse/takk'
      preLoaderRoute: typeof SelskapsanalyseTakkRouteImport
      parentRoute: typeof SelskapsanalyseRoute
    }
    '/rekruttererundersokelse/takk': {
      id: '/rekruttererundersokelse/takk'
      path: '/takk'
      fullPath: '/rekruttererundersokelse/takk'
      preLoaderRoute: typeof RekruttererundersokelseTakkRouteImport
      parentRoute: typeof RekruttererundersokelseRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/linkedin-callback': {
      id: '/auth/linkedin-callback'
      path: '/auth/linkedin-callback'
      fullPath: '/auth/linkedin-callback'
      preLoaderRoute: typeof AuthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbeidsgivere/$orgnr': {
      id: '/arbeidsgivere/$orgnr'
      path: '/$orgnr'
      fullPath: '/arbeidsgivere/$orgnr'
      preLoaderRoute: typeof ArbeidsgivereOrgnrRouteImport
      parentRoute: typeof ArbeidsgivereRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-applications': {
      id: '/_authenticated/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AuthenticatedMyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/job-leads': {
      id: '/_authenticated/job-leads'
      path: '/job-leads'
      fullPath: '/job-leads'
      preLoaderRoute: typeof AuthenticatedJobLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cover-letters': {
      id: '/_authenticated/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof AuthenticatedCoverLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about-me': {
      id: '/_authenticated/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AuthenticatedAboutMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/selskapsanalyse/analysedatabase/': {
      id: '/selskapsanalyse/analysedatabase/'
      path: '/analysedatabase'
      fullPath: '/selskapsanalyse/analysedatabase/'
      preLoaderRoute: typeof SelskapsanalyseAnalysedatabaseIndexRouteImport
      parentRoute: typeof SelskapsanalyseRoute
    }
    '/rekruttererundersokelse/resultater/': {
      id: '/rekruttererundersokelse/resultater/'
      path: '/resultater'
      fullPath: '/rekruttererundersokelse/resultater/'
      preLoaderRoute: typeof RekruttererundersokelseResultaterIndexRouteImport
      parentRoute: typeof RekruttererundersokelseRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer-analysis/': {
      id: '/_authenticated/offer-analysis/'
      path: '/offer-analysis'
      fullPath: '/offer-analysis/'
      preLoaderRoute: typeof AuthenticatedOfferAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/next-steps/': {
      id: '/_authenticated/next-steps/'
      path: '/next-steps'
      fullPath: '/next-steps/'
      preLoaderRoute: typeof AuthenticatedNextStepsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview-prep/': {
      id: '/_authenticated/interview-prep/'
      path: '/interview-prep'
      fullPath: '/interview-prep/'
      preLoaderRoute: typeof AuthenticatedInterviewPrepIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employers/': {
      id: '/_authenticated/employers/'
      path: '/employers'
      fullPath: '/employers/'
      preLoaderRoute: typeof AuthenticatedEmployersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentation/': {
      id: '/_authenticated/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof AuthenticatedDocumentationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv-builder/': {
      id: '/_authenticated/cv-builder/'
      path: '/cv-builder'
      fullPath: '/cv-builder/'
      preLoaderRoute: typeof AuthenticatedCvBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/selskapsanalyse/analysedatabase/$id': {
      id: '/selskapsanalyse/analysedatabase/$id'
      path: '/analysedatabase/$id'
      fullPath: '/selskapsanalyse/analysedatabase/$id'
      preLoaderRoute: typeof SelskapsanalyseAnalysedatabaseIdRouteImport
      parentRoute: typeof SelskapsanalyseRoute
    }
    '/rekruttererundersokelse/resultater/full': {
      id: '/rekruttererundersokelse/resultater/full'
      path: '/resultater/full'
      fullPath: '/rekruttererundersokelse/resultater/full'
      preLoaderRoute: typeof RekruttererundersokelseResultaterFullRouteImport
      parentRoute: typeof RekruttererundersokelseRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-report': {
      id: '/api/public/ingest-report'
      path: '/api/public/ingest-report'
      fullPath: '/api/public/ingest-report'
      preLoaderRoute: typeof ApiPublicIngestReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/employers/$companyId': {
      id: '/_authenticated/employers/$companyId'
      path: '/employers/$companyId'
      fullPath: '/employers/$companyId'
      preLoaderRoute: typeof AuthenticatedEmployersCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentation/packages': {
      id: '/_authenticated/documentation/packages'
      path: '/documentation/packages'
      fullPath: '/documentation/packages'
      preLoaderRoute: typeof AuthenticatedDocumentationPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentation/library': {
      id: '/_authenticated/documentation/library'
      path: '/documentation/library'
      fullPath: '/documentation/library'
      preLoaderRoute: typeof AuthenticatedDocumentationLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentation/cases': {
      id: '/_authenticated/documentation/cases'
      path: '/documentation/cases'
      fullPath: '/documentation/cases'
      preLoaderRoute: typeof AuthenticatedDocumentationCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career/atom-review': {
      id: '/_authenticated/career/atom-review'
      path: '/career/atom-review'
      fullPath: '/career/atom-review'
      preLoaderRoute: typeof AuthenticatedCareerAtomReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/new': {
      id: '/_authenticated/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AuthenticatedApplicationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rekruttererundersokelse': {
      id: '/_authenticated/admin/rekruttererundersokelse'
      path: '/admin/rekruttererundersokelse'
      fullPath: '/admin/rekruttererundersokelse'
      preLoaderRoute: typeof AuthenticatedAdminRekruttererundersokelseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/regnskap': {
      id: '/_authenticated/admin/regnskap'
      path: '/admin/regnskap'
      fullPath: '/admin/regnskap'
      preLoaderRoute: typeof AuthenticatedAdminRegnskapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cv-test': {
      id: '/_authenticated/admin/cv-test'
      path: '/admin/cv-test'
      fullPath: '/admin/cv-test'
      preLoaderRoute: typeof AuthenticatedAdminCvTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/changelog': {
      id: '/_authenticated/admin/changelog'
      path: '/admin/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof AuthenticatedAdminChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/selskapsanalyse/preview-email': {
      id: '/api/public/selskapsanalyse/preview-email'
      path: '/api/public/selskapsanalyse/preview-email'
      fullPath: '/api/public/selskapsanalyse/preview-email'
      preLoaderRoute: typeof ApiPublicSelskapsanalysePreviewEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/selskapsanalyse/download': {
      id: '/api/public/selskapsanalyse/download'
      path: '/api/public/selskapsanalyse/download'
      fullPath: '/api/public/selskapsanalyse/download'
      preLoaderRoute: typeof ApiPublicSelskapsanalyseDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutMeRoute: typeof AuthenticatedAboutMeRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCoverLettersRoute: typeof AuthenticatedCoverLettersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedJobLeadsRoute: typeof AuthenticatedJobLeadsRoute
  AuthenticatedMyApplicationsRoute: typeof AuthenticatedMyApplicationsRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedAdminChangelogRoute: typeof AuthenticatedAdminChangelogRoute
  AuthenticatedAdminCvTestRoute: typeof AuthenticatedAdminCvTestRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminRegnskapRoute: typeof AuthenticatedAdminRegnskapRoute
  AuthenticatedAdminRekruttererundersokelseRoute: typeof AuthenticatedAdminRekruttererundersokelseRoute
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
  AuthenticatedApplicationsNewRoute: typeof AuthenticatedApplicationsNewRoute
  AuthenticatedCareerAtomReviewRoute: typeof AuthenticatedCareerAtomReviewRoute
  AuthenticatedDocumentationCasesRoute: typeof AuthenticatedDocumentationCasesRoute
  AuthenticatedDocumentationLibraryRoute: typeof AuthenticatedDocumentationLibraryRoute
  AuthenticatedDocumentationPackagesRoute: typeof AuthenticatedDocumentationPackagesRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
  AuthenticatedEmployersCompanyIdRoute: typeof AuthenticatedEmployersCompanyIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedCvBuilderIndexRoute: typeof AuthenticatedCvBuilderIndexRoute
  AuthenticatedDocumentationIndexRoute: typeof AuthenticatedDocumentationIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedEmployersIndexRoute: typeof AuthenticatedEmployersIndexRoute
  AuthenticatedInterviewPrepIndexRoute: typeof AuthenticatedInterviewPrepIndexRoute
  AuthenticatedNextStepsIndexRoute: typeof AuthenticatedNextStepsIndexRoute
  AuthenticatedOfferAnalysisIndexRoute: typeof AuthenticatedOfferAnalysisIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutMeRoute: AuthenticatedAboutMeRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCoverLettersRoute: AuthenticatedCoverLettersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedJobLeadsRoute: AuthenticatedJobLeadsRoute,
  AuthenticatedMyApplicationsRoute: AuthenticatedMyApplicationsRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedAdminChangelogRoute: AuthenticatedAdminChangelogRoute,
  AuthenticatedAdminCvTestRoute: AuthenticatedAdminCvTestRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminRegnskapRoute: AuthenticatedAdminRegnskapRoute,
  AuthenticatedAdminRekruttererundersokelseRoute:
    AuthenticatedAdminRekruttererundersokelseRoute,
  AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  AuthenticatedApplicationsNewRoute: AuthenticatedApplicationsNewRoute,
  AuthenticatedCareerAtomReviewRoute: AuthenticatedCareerAtomReviewRoute,
  AuthenticatedDocumentationCasesRoute: AuthenticatedDocumentationCasesRoute,
  AuthenticatedDocumentationLibraryRoute:
    AuthenticatedDocumentationLibraryRoute,
  AuthenticatedDocumentationPackagesRoute:
    AuthenticatedDocumentationPackagesRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  AuthenticatedEmployersCompanyIdRoute: AuthenticatedEmployersCompanyIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedCvBuilderIndexRoute: AuthenticatedCvBuilderIndexRoute,
  AuthenticatedDocumentationIndexRoute: AuthenticatedDocumentationIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedEmployersIndexRoute: AuthenticatedEmployersIndexRoute,
  AuthenticatedInterviewPrepIndexRoute: AuthenticatedInterviewPrepIndexRoute,
  AuthenticatedNextStepsIndexRoute: AuthenticatedNextStepsIndexRoute,
  AuthenticatedOfferAnalysisIndexRoute: AuthenticatedOfferAnalysisIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ArbeidsgivereRouteChildren {
  ArbeidsgivereOrgnrRoute: typeof ArbeidsgivereOrgnrRoute
  ArbeidsgivereIndexRoute: typeof ArbeidsgivereIndexRoute
}

const ArbeidsgivereRouteChildren: ArbeidsgivereRouteChildren = {
  ArbeidsgivereOrgnrRoute: ArbeidsgivereOrgnrRoute,
  ArbeidsgivereIndexRoute: ArbeidsgivereIndexRoute,
}

const ArbeidsgivereRouteWithChildren = ArbeidsgivereRoute._addFileChildren(
  ArbeidsgivereRouteChildren,
)

interface RekruttererundersokelseRouteChildren {
  RekruttererundersokelseTakkRoute: typeof RekruttererundersokelseTakkRoute
  RekruttererundersokelseIndexRoute: typeof RekruttererundersokelseIndexRoute
  RekruttererundersokelseResultaterFullRoute: typeof RekruttererundersokelseResultaterFullRoute
  RekruttererundersokelseResultaterIndexRoute: typeof RekruttererundersokelseResultaterIndexRoute
}

const RekruttererundersokelseRouteChildren: RekruttererundersokelseRouteChildren =
  {
    RekruttererundersokelseTakkRoute: RekruttererundersokelseTakkRoute,
    RekruttererundersokelseIndexRoute: RekruttererundersokelseIndexRoute,
    RekruttererundersokelseResultaterFullRoute:
      RekruttererundersokelseResultaterFullRoute,
    RekruttererundersokelseResultaterIndexRoute:
      RekruttererundersokelseResultaterIndexRoute,
  }

const RekruttererundersokelseRouteWithChildren =
  RekruttererundersokelseRoute._addFileChildren(
    RekruttererundersokelseRouteChildren,
  )

interface SelskapsanalyseRouteChildren {
  SelskapsanalyseTakkRoute: typeof SelskapsanalyseTakkRoute
  SelskapsanalyseIndexRoute: typeof SelskapsanalyseIndexRoute
  SelskapsanalyseAnalysedatabaseIdRoute: typeof SelskapsanalyseAnalysedatabaseIdRoute
  SelskapsanalyseAnalysedatabaseIndexRoute: typeof SelskapsanalyseAnalysedatabaseIndexRoute
}

const SelskapsanalyseRouteChildren: SelskapsanalyseRouteChildren = {
  SelskapsanalyseTakkRoute: SelskapsanalyseTakkRoute,
  SelskapsanalyseIndexRoute: SelskapsanalyseIndexRoute,
  SelskapsanalyseAnalysedatabaseIdRoute: SelskapsanalyseAnalysedatabaseIdRoute,
  SelskapsanalyseAnalysedatabaseIndexRoute:
    SelskapsanalyseAnalysedatabaseIndexRoute,
}

const SelskapsanalyseRouteWithChildren = SelskapsanalyseRoute._addFileChildren(
  SelskapsanalyseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ArbeidsgivereRoute: ArbeidsgivereRouteWithChildren,
  LoginRoute: LoginRoute,
  MarkedsinnsiktRoute: MarkedsinnsiktRoute,
  PersonvernRoute: PersonvernRoute,
  RekruttererundersokelseRoute: RekruttererundersokelseRouteWithChildren,
  SelskapsanalyseRoute: SelskapsanalyseRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLinkedinCallbackRoute: AuthLinkedinCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicIngestReportRoute: ApiPublicIngestReportRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicSelskapsanalyseDownloadRoute: ApiPublicSelskapsanalyseDownloadRoute,
  ApiPublicSelskapsanalysePreviewEmailRoute:
    ApiPublicSelskapsanalysePreviewEmailRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
